### ISSUE TITLE
SublimeInfo not found

### ISSUE THREAD

**Issue by AbdealiJK** [twolfson/sublime-plugin-tests#32]
```
tests/CoalaCommandTest.py:3: in <module>
    from sublime_plugin_tests import framework
/usr/lib/python3.4/site-packages/sublime_plugin_tests/__init__.py:1: in <module>
    from .framework import TestCase
/usr/lib/python3.4/site-packages/sublime_plugin_tests/framework.py:6: in <module>
    from sublime_plugin_tests_base import Base
/usr/lib/python3.4/site-packages/sublime_plugin_tests_base/__init__.py:1: in <module>
    from .sublime_plugin_tests_base import Base
/usr/lib/python3.4/site-packages/sublime_plugin_tests_base/sublime_plugin_tests_base.py:10: in <module>
    from sublime_harness import Harness
/usr/lib/python3.4/site-packages/sublime_harness/__init__.py:1: in <module>
    from .sublime_harness import Harness
/usr/lib/python3.4/site-packages/sublime_harness/sublime_harness.py:8: in <module>
    import sublime_info
/usr/lib/python3.4/site-packages/sublime_info/__init__.py:2: in <module>
    from sublime_info import SublimeInfo
E   ImportError: cannot import name 'SublimeInfo'
```

I get the same error when doing `import sublime_info ` in shell:
```
$ python -c "import sublime_info"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/sublime_info/__init__.py", line 2, in <module>
    from sublime_info import SublimeInfo
ImportError: cannot import name 'SublimeInfo'
```

I can find the class in `/usr/lib/python3.4/site-packages/sublime_info/sublime_info.py` - so, Im not sure why it's unable to find it. I believe some import mismatch because the directory and file names are same ?

**Comment by twolfson** [comment]
Yea, strange. How did you install the package and what OS are you on?

**Comment by twolfson** [comment]
As a heads up, there is also a framework by randy3k which was developed later and should have better cross platform support:

https://github.com/randy3k/UnitTesting

**Comment by AbdealiJK** [comment]
I installed it using `pip` and Im on arch linux based (antergos
distribution).
This is on python 3.x - as arch uses that by default

**Comment by twolfson** [comment]
Thanks for the info and quick reply =)

It looks like I never dealt with Python 3 support -_-;;

https://github.com/twolfson/sublime-plugin-tests/blob/1.0.4/.travis.yml#L4

Can you try creating a virtualenv on Python 2 and seeing if it works there?

**Comment by AbdealiJK** [comment]
Ah, I see. I'll do that sometime tomorrow and get back to you

-----Original Message-----

**Comment by AbdealiJK** [comment]
Got some time so I tried it.

Yep - works fine in python 2.x
So, this becomes a duplicate of https://github.com/twolfson/sublime-plugin-tests/issues/26

Closing this - thanks :)

**Comment by twolfson** [comment]
Ah, cool. Yea, sorry about the Python 3 support =(
